### ISSUE TITLE
sudo docker build -t hcep-pdf-server:latest . does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by salos1982** [uyamazak/hcep-pdf-server#1]
Hello, I'm trying to install this service and hove troubles.
```
Step 8/25 : RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -   && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'   && apt-get update   && apt-get install -y google-chrome-stable --no-install-recommends   && rm -rf /var/lib/apt/lists/*   && rm -rf /src/*.deb
 ---> Running in 0afca7bbbc07
/bin/sh: 1: wget: not found
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation                                          
The command '/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -   && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'   && apt-get update   && apt-get install -y google-chrome-stable --no-install-recommends   && rm -rf /var/lib/apt/lists/*   && rm -rf /src/*.deb' returned a non-zero code: 255
```
It seems that the issue is because of the absence of quotes in Run commands
`wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub` work fine but 
`/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub` does not work

**Comment by uyamazak** [comment]
Hello, thank you for making issue.

Is the problem in the following line?

`RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \`
https://github.com/uyamazak/hcep-pdf-server/blob/master/Dockerfile#L16

I don't have an Ubuntu 20.04 environment on hand right now, so I'd be happy to do a pull request if you'd like.

**Comment by salos1982** [comment]
Yes issue in this line. I found solution. It seems that current version of base docker image does not contain wget. So adding `apt install wget` helped me.

**Comment by uyamazak** [comment]
Thank you, I was able to reproduce errors in my environment, so I fixed it and committed it.
