### ISSUE TITLE
Modify user-agent

### ISSUE THREAD

**Issue by geimist** [uyamazak/hcep-pdf-server#4]
Any websites don‘t allow access from chrome-headless (show a 404). In this case, to modify the user-agent is very helpful.
How can I do this with hcep-pdf-server in Docker?

The follow command don‘t work:
``curl -H "User-Agent:Safari/537.36" "http://localhost:8000?url=https://www.apple.com/de/shop/" -o hcep-pdf-get.pdf ``

**Comment by uyamazak** [comment]
Thank you for this issue.
Now I remake this with TypeScript and new version of puppeteer.
so I will make it taking this issue into consideration.

**Comment by geimist** [comment]
Thank you!
In my opinion, the easiest thing would be to provide an environment variable for this.

**Comment by uyamazak** [comment]
I created a new repository.

https://github.com/uyamazak/hc-pdf-server

You can change the User-Agent with the following environment variable.

**HCPDF_USER_AGENT**

Any feedback would be appreciated!
